### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by smurfix** [chanusukarno/generator-angular-gulp-bower#1]
After doing  a fresh install (via npm), and running yo:

smurf@desk:~/bla/xx$ nodejs node_modules/gulp/bin/gulp.js 
[07:23:54] Using gulpfile ~/bla/xx/Gulpfile.js
[07:23:54] Starting 'clean'...
[07:23:55] Finished 'clean' after 84 ms
[07:23:55] Starting 'default'...
[07:23:55] Starting 'styles'...
[07:23:55] Starting 'scripts'...
[07:23:55] Starting 'partials'...
[07:23:55] Starting 'images'...
[07:23:56] Finished 'default' after 946 ms
[07:23:56] gulp-size: total 0 B
[07:23:56] Finished 'styles' after 951 ms
[07:23:56] gulp-size: total 0 B
[07:23:56] Finished 'images' after 430 ms

/home/smurf/bla/xx/app/scripts/mainApp.js
  line 1  col 1   Use the function form of "use strict".
  line 2  col 13  'angular' is not defined.

✖ 2 problems

/home/smurf/bla/xx/app/scripts/controllers/sampleController.js
  line 4  col 1   Use the function form of "use strict".
  line 5  col 24  'angular' is not defined.

✖ 2 problems

[07:23:56] gulp-size: total 341 B
[07:23:56] Finished 'partials' after 533 ms

/home/smurf/bla/xx/app/scripts/directives/sampleDirective.js
  line 4  col 1   Use the function form of "use strict".
  line 5  col 23  'angular' is not defined.

✖ 2 problems

/home/smurf/bla/xx/app/scripts/filters/sampleFilter.js
  line 4   col 1   Use the function form of "use strict".
  line 5   col 21  'angular' is not defined.
  line 12  col 13  'console' is not defined.

✖ 3 problems

/home/smurf/bla/xx/app/scripts/services/sampleService.js
  line 4  col 1   Use the function form of "use strict".
  line 5  col 15  'require' is not defined.

✖ 2 problems

/home/smurf/bla/xx/app/scripts/utility/constant.js
  line 4  col 1   Use the function form of "use strict".
  line 5  col 23  'angular' is not defined.

✖ 2 problems

/home/smurf/bla/xx/app/scripts/utility/util.js
  line 4  col 1   Use the function form of "use strict".
  line 5  col 21  'angular' is not defined.

✖ 2 problems

[07:23:56] gulp-size: total 3.09 kB
[07:23:56] Finished 'scripts' after 712 ms
[07:23:56] Starting 'html'...

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Transform.emit (events.js:74:15)
    at Transform.onerror (/home/smurf/bla/xx/node_modules/gulp/node_modules/vinyl-fs/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_readable.js:588:12)
    at Transform.emit (events.js:95:17)
    at Transform.<anonymous> (/home/smurf/bla/xx/node_modules/gulp-useref/index.js:76:42)
    at Array.forEach (native)
    at Transform.<anonymous> (/home/smurf/bla/xx/node_modules/gulp-useref/index.js:66:35)
    at Array.forEach (native)
    at Transform.<anonymous> (/home/smurf/bla/xx/node_modules/gulp-useref/index.js:44:36)
    at Array.forEach (native)
smurf@desk:~/bla/xx$ ls
}}}

**Comment by ghost** [comment]
still broken ....
